### ISSUE TITLE
QUESTION - How to adjust severity of tests?

### ISSUE THREAD

**Issue by mvtemple** [fivetran/dbt_iterable#14]
**Are you a Fivetran customer?** 
Yes, Meera Temple, consultant @ Ephemeral Tattoo

**Your Question**
I'm getting a few failing dbt tests from the package. I'd like to reduce the severity of some of these packages, as I'm pretty sure these are failing due to some quirks in the way our Iterable folks have set up our campaigns. What's the best way to do that?

Despite adding the severity flag in the iterable.yml file, my dbt prod instance is still running these tests as originally written:

![image](https://user-images.githubusercontent.com/83354336/148794667-01992c18-f9de-4a42-9bbc-faecfb4bc2bd.png)

**Additional context**

**Please indicate the level of urgency and business impact of this request**

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mvtemple, thanks so much for opening this question!

If this is a result of your Iterable campaigns being set up with some quirks that the package is not intended to handle, you should be able to override the severity of the tests directly in your root `dbt_project.yml` using the configurations highlighted in these [dbt docs](https://docs.getdbt.com/reference/test-configs#available-configurations) for configuring tests.

If I am reading the docs correctly then you should be able to achieve what you want by adding the below to your `dbt_project.yml`:
```yml
## your dbt_project.yml
tests:
  iterable:
    iterable__campaigns:
      +severity: warn
```

You may need to adjust the spacing since GitHub isn't the best at allowing you to indent properly haha. Please let me know if this works on your end!

**Comment by mvtemple** [comment]
@fivetran-joemarkiewicz thank you so much!! I didn't realize this was something I could define in `dbt_project`, super helpful!
